### ISSUE TITLE
Error: Response interpr. failed:

### ISSUE THREAD

**Issue by TBR-BRD** [RhinoDevel/nodejs-fritzbox#1]
Hello, i have the error:

Error: Response interpr. failed: "<HTML><HEAD><TITLE>401 Unauthorized (ERR_NONE)</TITLE></HEAD><BODY><H1>401 Unauthorized</H1><BR>ERR_NONE<HR><B>Webserver</B> Thu, 25 Apr 2024 09:24:53 GMT</BODY></HTML>
"!
null

I have a 7590, and, can u please add MQTT?

Thank you

**Comment by RhinoDevel** [comment]
You need to configure your Fritzbox to allow these kind of requests.

**Comment by RhinoDevel** [comment]
For MQTT, take a look at [my other related project](https://github.com/RhinoDevel/nodejs-fritzbox-mqtt).
